# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 19:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accessories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=50)),
                ('catalog_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('product_desc', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
                ('stone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.StoneType')),
            ],
        ),
    ]
