# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0002_auto_20151226_1953'),
        ('Category', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_desc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('barcode', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer', to='Category.Category')),
                ('loss_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Loss')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.Material')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='loss_type',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='material',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('product_id', 'category')]),
        ),
    ]
