# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0004_auto_20160114_1009'),
        ('Product', '0003_auto_20160107_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Accessories.StoneType'),
            preserve_default=False,
        ),
    ]
