# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Product', '0004_product_stone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.SubCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Loss'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accessories.StoneType'),
        ),
    ]
