# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 10:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20160114_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
