# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_product_stones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stones',
            field=models.ManyToManyField(to='Accessories.StoneType'),
        ),
    ]
