# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20160114_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stones',
        ),
    ]
