# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0006_materialprice'),
        ('Product', '0010_remove_product_stones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
                ('stone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.StoneType')),
            ],
        ),
    ]
