# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_line_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
            preserve_default=False,
        ),
    ]
