# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 19:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100, unique=True)),
                ('loss', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('manf_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('material', models.CharField(choices=[('gold', 'GOLD'), ('silver', 'SILVER')], default='gold', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='j_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('category', 'sub_category_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('j_type', 'category_name')]),
        ),
    ]
