# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 19:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gRate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sRate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rate_per_carat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('StoneType_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessories.Stone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stonetype',
            unique_together=set([('StoneType_id', 'Stone')]),
        ),
    ]
