# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0004_auto_20160114_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='goldPrice',
        ),
        migrations.RemoveField(
            model_name='material',
            name='materialDate',
        ),
        migrations.RemoveField(
            model_name='material',
            name='silverPrice',
        ),
        migrations.AddField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
